osx_image: xcode10.2
language: objective-c

script:
- xcodebuild test -project SwiftColor.xcodeproj -scheme SwiftColor-iOSTests -destination "name=iPhone X"
- xcodebuild clean build -project SwiftColor.xcodeproj -scheme SwiftColor-iOS
- xcodebuild test -project SwiftColor.xcodeproj -scheme SwiftColor-macOSTests -destination "arch=x86_64"
- xcodebuild clean build -project SwiftColor.xcodeproj -scheme SwiftColor-macOS 
- xcodebuild clean build -project SwiftColor.xcodeproj -scheme SwiftColor-watchOS
- xcodebuild test -project SwiftColor.xcodeproj -scheme SwiftColor-tvOSTests -destination "name=Apple TV"
- xcodebuild clean build -project SwiftColor.xcodeproj -scheme SwiftColor-tvOS